const icelandBeer = [
  {
    productName: 'Old Speckled Hen Distinctive English Pale Ale 500ml',
    price: 180,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/old-speckled-hen-distinctive-english-pale-ale-500ml/64513.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/old_speckled_hen_distinctive_english_pale_ale_500ml_64513_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 116,
  },
  {
    productName: "Sharp's Doom Bar Amber Ale 500ml",
    price: 180,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/sharps-doom-bar-amber-ale-500ml/58496.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/sharps_doom_bar_amber_ale_500ml_58496_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 121,
  },
  {
    productName: 'Wychwood Brewery Hobgoblin Ruby Beer 500ml',
    price: 180,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/wychwood-brewery-hobgoblin-ruby-beer-500ml/35982.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/wychwood_brewery_hobgoblin_ruby_beer_500ml_35982_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 155,
  },
  {
    productName: "John Smith's Extra Smooth Ale 4 x 440ml Cans",
    price: 425,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/john-smiths-extra-smooth-ale-4-x-440ml-cans/53436.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/John_Smiths_4x44_Extra_Smooth_Bitter_53436.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 1410,
  },
  {
    productName: 'Bishops Finger 500ml',
    price: 180,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/bishops-finger-500ml/19127.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/bishops_finger_500ml_19127_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 1396,
  },
  {
    productName: 'Old Speckled Hen English Pale Ale 4 x 500ml',
    price: 495,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/old-speckled-hen-english-pale-ale-4-x-500ml/67889.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/old_speckled_hen_english_pale_ale_4_x_500ml_67889_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 1436,
  },
  {
    productName: "John Smith's Extra Smooth Ale 10 x 440ml Cans",
    price: 950,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/john-smiths-extra-smooth-ale-10-x-440ml-cans/74572.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/John_Smiths_104_Extra_Smooth_74572.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 3083,
  },
  {
    productName: 'Old Speckled Hen Distinctive English Pale Ale 4 x 440ml',
    price: 435,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/old-speckled-hen-distinctive-english-pale-ale-4-x-440ml/83122.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/old_speckled_hen_distinctive_english_pale_ale_4_x_440ml_83122_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 3635,
  },
  {
    productName: 'Old Speckled Hen English Pale Ale 10 x 440ml',
    price: 1100,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/old-speckled-hen-english-pale-ale-10-x-440ml/83328.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/old_speckled_hen_english_pale_ale_10_x_440ml_83328_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 1429,
  },
  {
    productName: 'Newcastle Brown Ale 550ml Bottle',
    price: 180,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/newcastle-brown-ale-550ml-bottle/1529.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Newcastle_Brown_Ale_550ml_Bottle_1529_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 1395,
  },
  {
    productName: 'BrewDog Punk IPA Post Modern Classic 330ml',
    price: 180,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/brewdog-punk-ipa-post-modern-classic-330ml/69628.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/brewdog_punk_ipa_post_modern_classic_330ml_69628_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'ale',
    supermarket: 'Iceland',
    productID: 1518,
  },
  {
    productName: "Frosty Jack's Cider 2.5 Litres",
    price: 370,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/frosty-jacks-cider-2.5-litres/77074.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Frosty_Jacks_25l_Original_Apple_Cider_77074.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3756,
  },
  {
    productName: 'Blackthorn Reserve 3 Litres',
    price: 370,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/blackthorn-reserve-3-litres/45046.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Blackthorn_3ltr_Cider_45046_1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3757,
  },
  {
    productName: 'Kopparberg Premium Cider with Strawberry & Lime 10 x 330ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/kopparberg-premium-cider-with-strawberry-and-lime-10-x-330ml/68018.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/kopparberg_premium_cider_with_strawberry_lime_10_x_330ml_68018_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3050,
  },
  {
    productName: 'Strongbow Original Cider 4 x 440ml Cans',
    price: 365,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/strongbow-original-cider-4-x-440ml-cans/80375.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/strongbow_original_cider_4_x_440ml_cans_80375_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 248,
  },
  {
    productName: 'Henry Westons Vintage Cider 500ml',
    price: 200,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/henry-westons-vintage-cider-500ml/78880.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/henry_westons_vintage_cider_500ml_78880_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 235,
  },
  {
    productName: 'Magners Irish Cider Original Apple 4 x 568ml',
    price: 400,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/magners-irish-cider-original-apple-4-x-568ml/64465.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Magners_4x56_Original_Cider_64465_1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3759,
  },
  {
    productName: 'Scrumpy Jack Premium British Cider 4 x 440ml Cans',
    price: 380,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/scrumpy-jack-premium-british-cider-4-x-440ml-cans/67975.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/scrumpy_jack_premium_british_cider_4_x_440ml_cans_67975_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 1544,
  },
  {
    productName: 'Thatchers Gold Cider 4 x 440ml',
    price: 400,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/thatchers-gold-cider-4-x-440ml/73768.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/thatchers_gold_cider_4_x_440ml_73768_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 233,
  },
  {
    productName: "Frosty Jack's Cider 4 x 500ml",
    price: 345,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/frosty-jacks-cider-4-x-500ml/35921.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/frosty_jacks_cider_4_x_500ml_35921_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3760,
  },
  {
    productName: 'K Cider 4 x 440ml',
    price: 450,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/k-cider-4-x-440ml/41457.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/k_cider_4_x_440ml_41457_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3761,
  },
  {
    productName: 'Strongbow Dark Fruit Cider 4 x 440ml Cans',
    price: 500,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/strongbow-dark-fruit-cider-4-x-440ml-cans/72586.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/strongbow_dark_fruit_cider_4_x_440ml_cans_72586_T517.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 1557,
  },
  {
    productName: 'Old Rosie The Original Cloudy Cider 2 Litre',
    price: 450,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/old-rosie-the-original-cloudy-cider-2-litre/77664.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Old_Rosie_2ltr_Cloudy_Cider_77664.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 262,
  },
  {
    productName: 'Kopparberg Strawberry & Lime 4 x 330ml',
    price: 500,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/kopparberg-strawberry-and-lime-4-x-330ml/68027.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/kopparberg_strawberry_lime_4_x_330ml_68027_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 292,
  },
  {
    productName: 'Thatchers Gold Cider 10 x 440ml',
    price: 900,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/thatchers-gold-cider-10-x-440ml/82492.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/thatchers_gold_cider_10_x_440ml_82492_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 1523,
  },
  {
    productName: 'Kopparberg Mixed Fruit 4 x 330ml',
    price: 500,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/kopparberg-mixed-fruit-4-x-330ml/68026.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/kopparberg_mixed_fruit_4_x_330ml_68026_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 284,
  },
  {
    productName: 'Thatchers Haze Cider 4 x 440ml',
    price: 425,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/thatchers-haze-cider-4-x-440ml/73770.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/thatchers_haze_cider_4_x_440ml_73770_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 230,
  },
  {
    productName: 'Strongbow Original Cider 18 x 440ml Cans',
    price: 1325,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/strongbow-original-cider-18-x-440ml-cans/80376.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/strongbow_original_cider_18_x_440ml_cans_80376_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 1526,
  },
  {
    productName: 'Thatchers Haze Cider 10 x 440ml',
    price: 950,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/thatchers-haze-cider-10-x-440ml/83804.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/thatchers_haze_cider_10_x_440ml_83804_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 1524,
  },
  {
    productName: 'Healeys Cyder Rattler Cornish Cloudy Cyder 8 x 330ml',
    price: 1100,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/healeys-cyder-rattler-cornish-cloudy-cyder-8-x-330ml/84093.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/healeys_cyder_rattler_cornish_cloudy_cyder_8_x_330ml_84093_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 3762,
  },
  {
    productName: 'Strongbow Dark Fruit Cider 10 x 440ml Cans',
    price: 1250,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/strongbow-dark-fruit-cider-10-x-440ml-cans/72836.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/strongbow_dark_fruit_cider_10_x_440ml_cans_72836_T517.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'cider',
    supermarket: 'Iceland',
    productID: 278,
  },
  {
    productName: 'Carlsberg Lager Beer 18 x 440ml',
    price: 1300,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carlsberg-lager-beer-18-x-440ml/76993.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carlsberg_lager_beer_18_x_440ml_76993_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1304,
  },
  {
    productName: 'Carling Original Lager 18 x 440ml',
    price: 1300,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carling-original-lager-18-x-440ml/76818.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carling_original_lager_18_x_440ml_76818_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1286,
  },
  {
    productName: "Foster's Lager Beer 18 x 440ml Cans",
    price: 1300,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/fosters-lager-beer-18-x-440ml-cans/72566.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/fosters_lager_beer_18_x_440ml_cans_72566_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1301,
  },
  {
    productName: 'Stella Artois Belgium Premium Lager Beer Cans 10 x 440ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/stella-artois-belgium-premium-lager-beer-cans-10-x-440ml/84139.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/stella_artois_belgium_premium_lager_beer_cans_10_x_440ml_84139_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1355,
  },
  {
    productName: 'Heineken Premium Lager Beer 12 x 330ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/heineken-premium-lager-beer-12-x-330ml/80669.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/heineken_premium_lager_beer_12_x_330ml_80669_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1260,
  },
  {
    productName: 'Budweiser King of Beers Lager Beer 12 x 300ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/budweiser-king-of-beers-lager-beer-12-x-300ml/72097.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/budweiser_king_of_beers_lager_beer_12_x_300ml_72097_T596.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3656,
  },
  {
    productName: 'San Miguel Premium Lager Beer 12 x 330ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/san-miguel-premium-lager-beer-12-x-330ml/64715.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/san_miguel_premium_lager_beer_12_x_330ml_64715_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 177,
  },
  {
    productName: 'Coors Light Lager 15 x 330ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/coors-light-lager-15-x-330ml/68033.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Coors_15pk_Light_Beer_68033.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3763,
  },
  {
    productName: 'Carlsberg Export Lager Beer 4 x 568ml',
    price: 475,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carlsberg-export-lager-beer-4-x-568ml/54194.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carlsberg_export_lager_beer_4_x_568ml_54194_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3865,
  },
  {
    productName: 'Birra Moretti Lager Beer 660ml Bottle',
    price: 195,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/birra-moretti-lager-beer-660ml-bottle/67964.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/birra_moretti_lager_beer_660ml_bottle_67964_T517.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1259,
  },
  {
    productName: 'Guinness Draught Stout Beer 10 x 440ml Can',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/guinness-draught-stout-beer-10-x-440ml-can/82356.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/guinness_draught_stout_beer_10_x_440ml_can_82356_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'stout',
    supermarket: 'Iceland',
    productID: 151,
  },
  {
    productName: 'Carlsberg Lager Beer 4 x 568ml',
    price: 425,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carlsberg-lager-beer-4-x-568ml/46160.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carlsberg_lager_beer_4_x_568ml_46160_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 205,
  },
  {
    productName: 'Skol Lager Beer 4x440ml',
    price: 200,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/skol-lager-beer-4x440ml/53819.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/skol_lager_beer_4x440ml_53819_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3764,
  },
  {
    productName: 'Stella Artois Belgium Premium Lager Beer Cans 4 x 568ml',
    price: 575,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/stella-artois-belgium-premium-lager-beer-cans-4-x-568ml/83776.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/stella_artois_belgium_premium_lager_beer_cans_4_x_568ml_83776_T596.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1363,
  },
  {
    productName: 'San Miguel Premium Lager Beer 660ml',
    price: 195,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/san-miguel-premium-lager-beer-660ml/66340.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/san_miguel_premium_lager_beer_660ml_66340_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1266,
  },
  {
    productName: 'San Miguel Premium Lager Beer 4 x 440ml',
    price: 460,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/san-miguel-premium-lager-beer-4-x-440ml/54036.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/san_miguel_premium_lager_beer_4_x_440ml_54036_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1289,
  },
  {
    productName: 'Heineken Lager Beer 650ml',
    price: 195,
    offer: '3 for £5.00',
    link: 'https://www.iceland.co.uk/p/heineken-lager-beer-650ml/67963.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/heineken_lager_beer_650ml_67963_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1320,
  },
  {
    productName: 'Carling Original Lager 10 x 440ml',
    price: 800,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carling-original-lager-10-x-440ml/75771.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carling_original_lager_10_x_440ml_75771_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3765,
  },
  {
    productName: 'Sol Original Lager Beer 12 x 330ml Bottles',
    price: 900,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/sol-original-lager-beer-12-x-330ml-bottles/79891.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/sol_original_lager_beer_12_x_330ml_bottles_79891_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1299,
  },
  {
    productName: 'Guinness Draught Stout Beer 4 x 440ml Can',
    price: 460,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/guinness-draught-stout-beer-4-x-440ml-can/6278.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/guinness_draught_stout_beer_4_x_440ml_can_6278_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'stout',
    supermarket: 'Iceland',
    productID: 1256,
  },
  {
    productName: "Tennent's Lager Beer 10 x 440ml",
    price: 900,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/tennents-lager-beer-10-x-440ml/61034.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/tennents_lager_beer_10_x_440ml_61034_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3766,
  },
  {
    productName: "Foster's Lager Beer 4 x 440ml Cans",
    price: 375,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/fosters-lager-beer-4-x-440ml-cans/6311.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Fosters_4pk_Fosters_Lager_6311.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1313,
  },
  {
    productName: 'Carling Original Lager 4 x 440ml',
    price: 360,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carling-original-lager-4-x-440ml/53422.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carling_original_lager_4_x_440ml_53422_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1315,
  },
  {
    productName: 'Desperados Tequila Lager Beer 3 x 330ml Bottles',
    price: 445,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/desperados-tequila-lager-beer-3-x-330ml-bottles/67966.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/desperados_tequila_lager_beer_3_x_330ml_bottles_67966_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1337,
  },
  {
    productName: 'Holsten Pils Lager Beer 4 x 440ml',
    price: 400,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/holsten-pils-lager-beer-4-x-440ml/6284.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/holsten_pils_lager_beer_4_x_440ml_6284_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1309,
  },
  {
    productName: 'Desperados Tequila Lager Beer 650ml Bottle',
    price: 285,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/desperados-tequila-lager-beer-650ml-bottle/66347.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/desperados_tequila_lager_beer_650ml_bottle_66347_T517.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1338,
  },
  {
    productName: 'Budweiser Beer 4 x 300ml',
    price: 400,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/budweiser-beer-4-x-300ml/72096.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/budweiser_beer_4_x_300ml_72096_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3641,
  },
  {
    productName: 'Corona Lager Beer Bottles 4 x 330ml',
    price: 500,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/corona-lager-beer-bottles-4-x-330ml/72302.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/corona_lager_beer_bottles_4_x_330ml_72302_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1264,
  },
  {
    productName: 'Budweiser Lager Beer Bottles 20 x 300ml',
    price: 1200,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/budweiser-lager-beer-bottles-20-x-300ml/72749.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/budweiser_lager_beer_bottles_20_x_300ml_72749_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1305,
  },
  {
    productName: 'Warsteiner Premium Beer 0.66L',
    price: 175,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/warsteiner-premium-beer-0.66l/83016.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/warsteiner_premium_beer_066l_83016_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1298,
  },
  {
    productName: 'Budweiser Beer 4 x 568ml',
    price: 575,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/budweiser-beer-4-x-568ml/72095.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/budweiser_beer_4_x_568ml_72095_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3651,
  },
  {
    productName: "Tennent's Lager Beer 4 x 568ml",
    price: 480,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/tennents-lager-beer-4-x-568ml/33268.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/tennents_lager_beer_4_x_568ml_33268_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3767,
  },
  {
    productName: 'Birra Moretti Lager Beer 4 x 330ml Bottles',
    price: 475,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/birra-moretti-lager-beer-4-x-330ml-bottles/79892.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/birra_moretti_lager_beer_4_x_330ml_bottles_79892_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1263,
  },
  {
    productName: 'Peroni Nastro Azzurro 620ml',
    price: 270,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/peroni-nastro-azzurro-620ml/66345.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Peroni_620_Peroni_Lager_Beer_66345.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1267,
  },
  {
    productName: 'Innis & Gunn Lager Beer 4 x 440ml',
    price: 450,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/innis-and-gunn-lager-beer-4-x-440ml/79280.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/innis_gunn_lager_beer_4_x_440ml_79280_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 212,
  },
  {
    productName: 'Cobra Premium Beer 12 x 330ml',
    price: 1000,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/cobra-premium-beer-12-x-330ml/77113.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Cobra_12pk_World_Beer_77113.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3768,
  },
  {
    productName: 'Heineken Premium Lager Beer 4 x 330ml',
    price: 450,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/heineken-premium-lager-beer-4-x-330ml/79899.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/heineken_premium_lager_beer_4_x_330ml_79899_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3769,
  },
  {
    productName: "Beck's Blue Alcohol Free Beer Bottles 6 x 275ml",
    price: 375,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/becks-blue-alcohol-free-beer-bottles-6-x-275ml/74983.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/becks_blue_alcohol_free_beer_bottles_6_x_275ml_74983_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'beer low alcohol',
    supermarket: 'Iceland',
    productID: 1316,
  },
  {
    productName: 'Red Stripe Jamaica Lager Beer 4 x 440ml Cans',
    price: 445,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/red-stripe-jamaica-lager-beer-4-x-440ml-cans/73087.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Red_Stripe_4pk_Jamaican_Lager_Beer_73087.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3648,
  },
  {
    productName: "Tennent's Light Beer 4 x 300ml",
    price: 350,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/tennents-light-beer-4-x-300ml/84105.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/tennents_light_beer_4_x_300ml_84105_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3770,
  },
  {
    productName: 'Kronenbourg 1664 Lager Beer 4 x 440ml Cans',
    price: 450,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/kronenbourg-1664-lager-beer-4-x-440ml-cans/18428.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/Kronenbourg_1664_Lager_Beer_4_x_440ml_Cans_18428_T517.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 187,
  },
  {
    productName: 'Guinness Foreign Extra Stout 4 x 325ml',
    price: 650,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/guinness-foreign-extra-stout-4-x-325ml/58693.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/guinness_foreign_extra_stout_4_x_325ml_58693_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'stout',
    supermarket: 'Iceland',
    productID: 1469,
  },
  {
    productName: 'Budweiser Budvar Original Czech Lager 5L',
    price: 1600,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/budweiser-budvar-original-czech-lager-5l/60633.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/budweiser_budvar_original_czech_lager_5l_60633_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3771,
  },
  {
    productName: 'Carlsberg Lager Beer 4 x 500ml',
    price: 449,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carlsberg-lager-beer-4-x-500ml/53818.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carlsberg_lager_beer_4_x_500ml_53818_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3772,
  },
  {
    productName: 'Carlsberg Export Lager Beer 4 x 500ml',
    price: 499,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/carlsberg-export-lager-beer-4-x-500ml/75883.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/carlsberg_export_lager_beer_4_x_500ml_75883_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3773,
  },
  {
    productName: 'Amstel Lager Beer 12 x 300ml Bottles',
    price: 850,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/amstel-lager-beer-12-x-300ml-bottles/76439.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/amstel_lager_beer_12_x_300ml_bottles_76439_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3844,
  },
  {
    productName: 'Amstel Lager Beer 4 x 440ml Cans',
    price: 400,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/amstel-lager-beer-4-x-440ml-cans/76440.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/amstel_lager_beer_4_x_440ml_cans_76440_T5.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1311,
  },
  {
    productName: 'Corona Lager Beer Bottles 10 x 330ml',
    price: 1100,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/corona-lager-beer-bottles-10-x-330ml/68993.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/corona_lager_beer_bottles_10_x_330ml_68993_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 1356,
  },
  {
    productName: 'Innis & Gunn Lager Beer 660ml',
    price: 195,
    offer: 'No offer',
    link: 'https://www.iceland.co.uk/p/innis-and-gunn-lager-beer-660ml/79281.html',
    image:
      'https://assets.iceland.co.uk/i/iceland/innis_gunn_lager_beer_660ml_79281_T1.jpg?$producttile$',
    drinkType: 'beer',
    drinkSubtype: 'lager',
    supermarket: 'Iceland',
    productID: 3774,
  },
];

module.exports = { icelandBeer };
